main/urls.py
from django.urls import path, include
from .views import valyutakurs, for_calculator, MainInfoListView, CreateMainInfo, UpdateMainInfo, main_info_delete, MainInfoDetail

urlpatterns = [
    # path('', home, name='home'),
    # path('', ValyutaView.as_view(), name='home')
    path('', valyutakurs, name='home'),
    path('calculator/', for_calculator, name='calculator'),
    path('main_info/', MainInfoListView.as_view(), name='main_info'),
    path('create_info/', CreateMainInfo.as_view(), name='create_info'),
    path('update_info/<int:id>/', UpdateMainInfo.as_view(), name='update_info'),
    path('delete_info/<int:id>/', main_info_delete, name='delete_info'),
    path('detail_info/<int:id>/', MainInfoDetail.as_view(), name='detail_info')
    # path('update_info/<int:id>/', UpdateMainInfo.as_view(), name='update_info')
]

membership/urls.py
from django.contrib import admin
from django.urls import path, include
from main.custom_errors import error_403, error_404, error_500
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

handler403 = error_403
handler404 = error_404
handler500 = error_500

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('main/', include(('main.urls', 'main'), namespace='main')),
    path('organizations/', include(('organizations.urls', 'organizations'), namespace='organizations')),
    path('i18n/', include('django.conf.urls.i18n')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#     path('organizations/', include(('organizations.urls', 'organizations'), namespace='organizations'))
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizations/urls.py
from django.contrib.auth.decorators import login_required
from django.http import request

from .views import *
from django.urls import path, include
from .helpers import get_currency


urlpatterns = [
    path('local-organizations/', login_required(AuthOrgListView.as_view()), name="auth_orgs"),
    path('create-local-org/', login_required(AuthOrgCreateView.as_view()), name="auth_create"),
    path('local-org-detail/<int:id>/', login_required(AuthOrganizationDetail.as_view()), name='auth_detail'),
    path('update-local-org/<int:id>/', login_required(AuthOrganUpdate.as_view()), name="auth_update"),
    path('delete-local-org/<int:id>/', login_required(authorgan_delete), name="auth_delete"),
    # end AuthOrgan

    # start InterOrgan
    path('inter-organizations/', login_required(InterOrgListView.as_view()), name="inter_orgs"),
    path('inter_detail/<int:id>/', login_required(InterOrganDetail.as_view()), name='inter_detail'),
    path('inter_create/', login_required(InterOrganCreate.as_view()), name='inter_create'),
    path('inter_update/<int:id>/', login_required(InterOrganUpdate.as_view()), name='inter_update'),
    path('inter_delete/<int:id>/', login_required(inter_organ_delete), name='inter_delete'),
    # end InterOrgan

    # start Currency Part
    path('currency/', login_required(CurrencyListView.as_view()), name="currencies"),
    path('currency_detail/<int:id>/', login_required(CurrencyDetail.as_view()), name='currency_detail'),
    path('currency_create/', login_required(CurrencyCreate.as_view()), name='currency_create'),
    path('currency_update/<int:id>/', login_required(CurrensyUpdate.as_view()), name='currency_update'),
    path('currency_delete/<int:id>/', login_required(currency_delete), name='currency_delete'),
    # End Currency part

    # Start MemberShipFee Part
    path('membership-fee/in-budget/', login_required(MembershipFeeConditionListViewInBudget.as_view()),
         name="membership_fees"),
    path('membership-fee/out-budget/', login_required(MembershipFeeConditionListViewOutBudget.as_view()),
         name="membership_fee_out"),

    path('membership_detail/<int:id>/', login_required(MemberShipDetail.as_view()), name='membership_detail'),
    path('membership_create/', login_required(MembershipFeeConditionCreateView.as_view()), name="membership_create"),
    path('member_update/<int:id>/', login_required(MemberShipUpdate.as_view()), name='membership_update'),
    path('member_delete/<int:id>/', login_required(member_delete), name='membership_delete'),
    # End MemberShipFee

    # // Start LinkedOrgs urls \\#
    path('linked-orgs/out-budget', login_required(LinkedOrgsListView.as_view()), name="linked_orgs"),
    path('linked-orgs/in-budget', login_required(LinkedOrgsListViewInBudget.as_view()), name="linked_orgs_in"),
    path('linked-org-create/', login_required(LinkedOrgsCreateView.as_view()), name="linked_org_create"),
    path('linked-org-update/<int:id>/', login_required(LinkedOrgsUpdateView.as_view()), name="linked_org_update"),
    path('linked-org-detail/<int:id>/', login_required(LinkedOrgsDetailView.as_view()), name="linked_org_detail"),
    path('linked-org-delete/<int:id>/', login_required(linked_org__delete), name="linked_org_delete"),
    # end linkedorgs

    # Start debts urls
    path('debts/<int:year>/', login_required(DebtListView.as_view()), name="debts_list"),
    path('debts-create/<int:year>/', login_required(DebtCreateView.as_view()), name="debt_create"),
    path('debts-update/<int:year>/<int:id>/', login_required(DebtUpdateView.as_view()), name="debt_update"),
    path('debts-delete/<int:year>/<int:id>/', login_required(debt_delete), name="debt_delete"),
    path('debts-detail/<int:year>/<int:id>/', login_required(DebtDetailView.as_view()), name="debt_detail"),
    # end debts urls

    # Start over payments
    path('over-payments/<int:year>/', login_required(OverPaymentListView.as_view()), name="over_payments_list"),
    path('over-payment-create/<int:year>/', login_required(OverPaymentCreateView.as_view()),
         name="over_payment_create"),
    path('over-payment-update/<int:year>/<int:id>/', login_required(OverPaymentUpdateView.as_view()),
         name="over_payment_update"),
    path('over-payment-delete/<int:year>/<int:id>/', login_required(over_payment_delete), name="over_payment_delete"),
    path('over-payment-detail/<int:year>/<int:id>/', login_required(OverPaymentDetailView.as_view()),
         name="over_payment_detail"),

    #  end Payments

    # Helpers

    path('inter-org-currency/', login_required(get_currency), name='inter_org_currency')
]

templates/currencies/currencies.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}

{% block title %}<title>{% trans 'Currencies'%}</title>{% endblock %}

  {% block links %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  {% endblock %}

{% block page_title %}
{% trans 'Pul birliklari'%}
{% endblock %}
  {% block breadcrumb %}
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{% url 'main:home' %}">{% trans 'Bosh sahifa'%}</a></li>
      <li class="breadcrumb-item active">{% trans 'Pul birliklari'%}</li>
    </ol>
  </div>
  {% endblock %}


    <!-- Main content -->
    {% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row mt-2">
          <div class="col-4">
              <div class="card" style="height: 97.348%">
                  <div class="card-header" style="background-color: #0d8ccb">
                      <h3 class="card-title text-white">{% trans 'Kalkulyator' %}</h3>
                  </div>
                  <div class="card-body">
                      <div class="w-75 mx-auto">
                          <div class="row align-items-center justify-content-around">
                              <div class="col-4">
                                  <img style="width: 30px; height: 30px" src="{% static 'images/cbuz.png' %}" alt="cb"><input id="cb" class="ml-3" type="checkbox" checked disabled>
                              </div>
                              <div class="col-4">
                                  <img style="width: 50px; height: 20px" src="{% static 'images/birja.png' %}" alt="birja"><input id="birja" class="ml-3" type="checkbox">
                              </div>
                          </div>
                          <div class="mt-3">
                              <label for="pul_birliklari" class="mt-3">{% trans "Pul birligini tanlang" %}</label>
                              <select class="custom-select" name="valyuta" id="cb_select">
                                  <option value="USD">USD</option>
                                  <option value="EUR">EUR</option>
                                  <option value="RUB">RUB</option>
                                  <option value="CAD">CAD</option>
                                  <option value="CHF">CHF</option>
                              </select>
{#                              <select class="custom-select" name="valyuta" id="birja_select">#}
{#                                  <option>USD</option>#}
{#                                  <option>EUR</option>#}
{#                              </select>#}
                              <label for="current_amount" class="mt-3">{% trans "Joriy kurs" %}</label>
                              <input class="form-control" disabled id="current_amount" type="text">
                              <label class="mt-4" for="input_amount">{% trans "Pul miqdorini kiriting" %}</label>
                              <input class="form-control" id="input_amount" type="text">
                              <label class="mt-3" for="result">{% trans "NATIJA" %}:</label>
                              <input class="form-control form-control-lg" type="text" disabled id="result">
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="col-8">
            <div class="card">
              <div class="card-header" style="background-color: #0d8ccb">
                <h3 class="card-title text-white">{% trans "To'lov amalga oshiriladigan pul birliklari ro'yxati"%}</h3>
              </div>
              <div class="card-body">
                <table id="example1" class="table table-hover text-center">
                  <thead>
                  <tr>
                    <th>{% trans "T/r" %}</th>
                    <th>{% trans 'Nomi'%}</th>
                    <th>{% trans 'Belgi'%}</th>
                    <th>{% trans 'Abbr'%}</th>
                      <th></th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for o in objects %}
                  <tr>
                    <td>{{ o.id }}</td>
                    {% if LANGUAGE_CODE == 'uz' %}
                    <td>{{ o.name_uz }}</td>
                    {% elif LANGUAGE_CODE == 'ru' %}
                    <td>{{ o.name_ru }}</td>
                    {% elif LANGUAGE_CODE == 'en' %}
                    <td>{{ o.name_en }}</td>
                    {% endif %}
                    <td>{{ o.sign }}</td>
                    <td>{{ o.abbr }}</td>
                    <td style="width: 2rem;" class="text-righ">
                        <div style="width: 2.25rem;" class="dropdown ml-auto">
                            <a class="btn btn-sm btn-icon-only text-light"
                               href="#" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-ellipsis-v text-dark"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                {% if user.role == 'Admin' %}
                                <a class="dropdown-item text-navy"
                                   href="{% url 'organizations:currency_update' o.id %}"><i class="fas fa-edit text-left"></i><span class="ml-3">{% trans "O'zgartirish" %}</span>
                                </a>
                                <a class="dropdown-item text-danger"
                                   href="{% url 'organizations:currency_delete' o.id %}"><i class="fas fa-trash text-left"></i><span class="ml-3">{% trans "O'chirish" %}</span>
                                </a>
                                {% endif %}
                                <a class="dropdown-item text-info"
                                   href="{% url 'organizations:currency_detail' o.id %}"><i class="fas fa-eye text-left"></i><span class="ml-3">{% trans "Ko'rish" %}</span>
                                </a>
                            </div>
                        </div>
                    </td>

                  </tr>
                  {% endfor %}

                  </tbody>
                </table>
                {% if user.role == "Admin" %}
                <div class="row justify-content-start mt-n3">
                  <div class="col-4 mt-n3">
                      <a href="{% url 'organizations:currency_create' %}" class="btn-lg btn-info">{% trans "Qo'shish"%}</a>
                  </div>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}



{% block script %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Page specific script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "info": false,
      "paging": 10,
      "responsive": true,
      "lengthChange": false,
      "autoWidth": false,
      "buttons": [
              {
                  extend: "excel",
                  className: 'btn btn-info',
                  exportOptions: {
                      columns: 'th:not(:last-child)'
                  }
              },
              {
                  extend: "pdf",
                  className: 'btn btn-info',
                  exportOptions: {
                      columns: 'th:not(:last-child)'
                  }
              },
              {
                  extend: "colvis",
                  className: 'btn btn-info'
              }
          ],
      "language": {
          "buttons": {
              "colvis": "{% trans "Ustun ko'rinishi"%}",
          },
          "paginate": {
              "previous": "{% trans "Avvalgi" %}",
              "next": "{% trans "Keyingi" %}",
          },
          "search": "{% trans 'Izlash'%}",
      },
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
  });
</script>
<script>
$(document).ready(function (){
    function data(data_type, currency_name){
        $.ajax({
            url: '/uz/main/calculator/',
            {#type: 'post',#}
            data: {
                'type':data_type,
                'name': currency_name
                {#'csrfmiddlewaretoken': {% csrf_token %}#}
            },
            dataType: 'json',
            success: function (data){
                $("#current_amount").val(data['price']);
            },
            fail: function (data){
                if (data){
                    console.log(data);
                    console.log('failure')
                }
            }
        })
        {#$.post('/main/calculator/', {item_data:data_type})#}
        {#    .done((response) => {#}
        {#        console.log(response)#}
        {#    }).fail((fail_response) => {#}
        {#        console.log(fail_response);#}
        {#        console.log('failed');#}
        {#    })#}
    }


    $("#birja_select").hide();
    let cb_check = $("#cb");
    let birja_check = $("#birja");
    let cb_options = $("#cb_select");
    let current_amount = $("#current_amount");
    let input_amount = $("#input_amount");
    let result = $("#result");
    let data_type = 'cb';

    birja_check.on('click', function (){
        if (birja_check.prop('checked') == true){
            $("#cb_select option[value='RUB']").hide();
            $("#cb_select option[value='CAD']").hide();
            $("#cb_select option[value='CHF']").hide();
            cb_check.prop('checked', false);
            {#whatever = data('birja').data;#}
            data_type = 'birja';
            console.log('checked');
        } else if (birja_check.prop('checked') == false) {
            $("#cb_select option[value='RUB']").show();
            $("#cb_select option[value='CAD']").show();
            $("#cb_select option[value='CHF']").show();
            {#console.log($("#cb_options option[value='RUB']").val();#}
            cb_check.prop('checked', true);
            data_type = 'cb';
            console.log('not checked');
            {#whatever = data('cb');#}
        }
    });

    cb_options.on('change', function (){
        let currency_name = $("#cb_select").find(':selected').text();
        if (birja_check.prop('checked') == true){
            data_type = 'birja';
        } else if (birja_check.prop('checked') == true){
            data_type = 'cb';
        }
        console.log(data_type);
        console.log(data(data_type, currency_name))
    });

    result.val(0)
    input_amount.keyup(function (){
        console.log(input_amount.val());
        console.log(current_amount.val())
        let r = 0;
        if (input_amount.val()){
            r = parseFloat(current_amount.val())*parseInt($("#input_amount").val());
        }
        result.val(r.toFixed(2));
        console.log(r)
    })

})
</script>
{% endblock %}

templates/currencies/currency_create.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>{% trans "Create organizations"%}</title>{% endblock %}

{% block links %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
{% endblock %}





{% block page_title %}
{% trans "Tashkilot qo'shish"%}
{% endblock %}

{% block breadcrumb %}
<div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{% url 'main:home' %}">{% trans 'Bosh sahifa'%}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizations:currencies' %}">{% trans 'Pul birliklari'%}</a></li>
      <li class="breadcrumb-item active">{% trans "Qo'shish"%}</li>
    </ol>
</div>
{% endblock %}


    <!-- Main content -->
    {% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-12 mx-auto" style="max-width: 96%">
            <!-- Input addon -->
            <div class="card mt-2">
              <div class="card-header" style="background-color: #0d8ccb">
                <h3 class="card-title">{% trans "Tashkilot ma'lumotlarini kiriting"%}</h3>
              </div>
              <div class="card-body">

                <form action="{% url 'organizations:currency_create' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            {{ form.name_uz | as_crispy_field }}
                        </div>
                        <div class="col">
                            {{ form.name_ru | as_crispy_field }}
                        </div>
                        <div class="col">
                            {{ form.name_en | as_crispy_field }}
                        </div>
                        <div class="col">
                            {{ form.sign | as_crispy_field }}
                        </div>
                        <div class="col">
                            {{ form.abbr | as_crispy_field }}
                        </div>
                    </div>
                    <div class="row justify-content-end mt-3">
                        <button type="submit" class="btn-lg btn-info mr-2">{% trans 'Saqlash'%}</button>
                    </div>
                </form>


              </div>
              <!-- /.card-body -->
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}


{% block script %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Page specific script -->
<script>
$(function () {
  bsCustomFileInput.init();
});
</script>
<script src="{% static 'imask/http_unpkg.com_imask.js' %}"></script>
<script>
    let element = document.getElementById('org_phone_id');
    let maskOptions = {
        mask: '+998(00) 000-00-00',
        {#lazy: false,#}
    };
    let mask = new IMask(element, maskOptions);
</script>

{% endblock %}

templates/currencies/currency_detail.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}

{% block title %}<title>{% trans 'Currencies'%}</title>{% endblock %}

  {% block links %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  {% endblock %}

{% block page_title %}
{% trans 'Pul birliklari'%}
{% endblock %}
  {% block breadcrumb %}
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{% url 'main:home' %}">{% trans 'Bosh sahifa'%}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizations:currencies' %}">{% trans 'Pul birliklari'%}</a></li>
      <li class="breadcrumb-item active">{% trans 'Batafsil'%}</li>
    </ol>
  </div>
  {% endblock %}


    <!-- Main content -->
    {% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card mt-2">
              <div class="card-header" style="background-color: #0d8ccb">
                <h3 class="card-title">{% trans "To'lov amalga oshiriladigan pul birliklari ro'yxati"%}</h3>
              </div>
              <div class="card-body">
                <table id="example1" class="table table-bordered table-hover text-center">
                  <thead class="bg-gray-light">
                  <tr>
                    <th>{% trans "T/r" %}</th>
                    <th>{% trans 'Nomi'%}</th>
                    <th>{% trans 'Belgi'%}</th>
                    <th>{% trans 'Abbr'%}</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    <td>{{ object.id }}</td>
                    {% if LANGUAGE_CODE == 'uz' %}
                    <td>{{ object.name_uz }}</td>
                    {% elif LANGUAGE_CODE == 'ru' %}
                    <td>{{ object.name_ru }}</td>
                    {% elif LANGUAGE_CODE == 'en' %}
                    <td>{{ object.name_en }}</td>
                    {% endif %}
                    <td>{{ object.sign }}</td>
                    <td>{{ object.abbr }}</td>
                  </tr>
                  </tbody>
                </table>
              </div>
              <div class="row justify-content-start mb-3 mt-n3">
                  <div class="col-1 btn-group" style="margin-left: 20px;">
                      <a href="{% url 'organizations:currencies' %}"  class="btn btn-outline-info"><i class="fas fa-angle-double-left"></i></a>
                      {% if user.role == "Admin" %}
                      <a href="{% url 'organizations:currency_update' object.id %}?from=currency_detail"  class="btn btn-outline-info"><i class="fas fa-edit"></i></a>
                      <a href="{% url 'organizations:currency_delete' object.id %}?from=currency_detail"  class="btn btn-outline-info"><i class="fas fa-trash"></i></a>
                      {% endif %}
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}



{% block script %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Page specific script -->
{% endblock %}