main/urls.py
from django.urls import path, include
from .views import valyutakurs, for_calculator, MainInfoListView, CreateMainInfo, UpdateMainInfo, main_info_delete, MainInfoDetail

urlpatterns = [
    # path('', home, name='home'),
    # path('', ValyutaView.as_view(), name='home')
    path('', valyutakurs, name='home'),
    path('calculator/', for_calculator, name='calculator'),
    path('main_info/', MainInfoListView.as_view(), name='main_info'),
    path('create_info/', CreateMainInfo.as_view(), name='create_info'),
    path('update_info/<int:id>/', UpdateMainInfo.as_view(), name='update_info'),
    path('delete_info/<int:id>/', main_info_delete, name='delete_info'),
    path('detail_info/<int:id>/', MainInfoDetail.as_view(), name='detail_info')
    # path('update_info/<int:id>/', UpdateMainInfo.as_view(), name='update_info')
]

membership/urls.py
from django.contrib import admin
from django.urls import path, include
from main.custom_errors import error_403, error_404, error_500
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

handler403 = error_403
handler404 = error_404
handler500 = error_500

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('main/', include(('main.urls', 'main'), namespace='main')),
    path('organizations/', include(('organizations.urls', 'organizations'), namespace='organizations')),
    path('i18n/', include('django.conf.urls.i18n')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#     path('organizations/', include(('organizations.urls', 'organizations'), namespace='organizations'))
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizations/urls.py
from django.contrib.auth.decorators import login_required
from django.http import request

from .views import *
from django.urls import path, include
from .helpers import get_currency


urlpatterns = [
    path('local-organizations/', login_required(AuthOrgListView.as_view()), name="auth_orgs"),
    path('create-local-org/', login_required(AuthOrgCreateView.as_view()), name="auth_create"),
    path('local-org-detail/<int:id>/', login_required(AuthOrganizationDetail.as_view()), name='auth_detail'),
    path('update-local-org/<int:id>/', login_required(AuthOrganUpdate.as_view()), name="auth_update"),
    path('delete-local-org/<int:id>/', login_required(authorgan_delete), name="auth_delete"),
    # end AuthOrgan

    # start InterOrgan
    path('inter-organizations/', login_required(InterOrgListView.as_view()), name="inter_orgs"),
    path('inter_detail/<int:id>/', login_required(InterOrganDetail.as_view()), name='inter_detail'),
    path('inter_create/', login_required(InterOrganCreate.as_view()), name='inter_create'),
    path('inter_update/<int:id>/', login_required(InterOrganUpdate.as_view()), name='inter_update'),
    path('inter_delete/<int:id>/', login_required(inter_organ_delete), name='inter_delete'),
    # end InterOrgan

    # start Currency Part
    path('currency/', login_required(CurrencyListView.as_view()), name="currencies"),
    path('currency_detail/<int:id>/', login_required(CurrencyDetail.as_view()), name='currency_detail'),
    path('currency_create/', login_required(CurrencyCreate.as_view()), name='currency_create'),
    path('currency_update/<int:id>/', login_required(CurrensyUpdate.as_view()), name='currency_update'),
    path('currency_delete/<int:id>/', login_required(currency_delete), name='currency_delete'),
    # End Currency part

    # Start MemberShipFee Part
    path('membership-fee/in-budget/', login_required(MembershipFeeConditionListViewInBudget.as_view()),
         name="membership_fees"),
    path('membership-fee/out-budget/', login_required(MembershipFeeConditionListViewOutBudget.as_view()),
         name="membership_fee_out"),

    path('membership_detail/<int:id>/', login_required(MemberShipDetail.as_view()), name='membership_detail'),
    path('membership_create/', login_required(MembershipFeeConditionCreateView.as_view()), name="membership_create"),
    path('member_update/<int:id>/', login_required(MemberShipUpdate.as_view()), name='membership_update'),
    path('member_delete/<int:id>/', login_required(member_delete), name='membership_delete'),
    # End MemberShipFee

    # // Start LinkedOrgs urls \\#
    path('linked-orgs/out-budget', login_required(LinkedOrgsListView.as_view()), name="linked_orgs"),
    path('linked-orgs/in-budget', login_required(LinkedOrgsListViewInBudget.as_view()), name="linked_orgs_in"),
    path('linked-org-create/', login_required(LinkedOrgsCreateView.as_view()), name="linked_org_create"),
    path('linked-org-update/<int:id>/', login_required(LinkedOrgsUpdateView.as_view()), name="linked_org_update"),
    path('linked-org-detail/<int:id>/', login_required(LinkedOrgsDetailView.as_view()), name="linked_org_detail"),
    path('linked-org-delete/<int:id>/', login_required(linked_org__delete), name="linked_org_delete"),
    # end linkedorgs

    # Start debts urls
    path('debts/<int:year>/', login_required(DebtListView.as_view()), name="debts_list"),
    path('debts-create/<int:year>/', login_required(DebtCreateView.as_view()), name="debt_create"),
    path('debts-update/<int:year>/<int:id>/', login_required(DebtUpdateView.as_view()), name="debt_update"),
    path('debts-delete/<int:year>/<int:id>/', login_required(debt_delete), name="debt_delete"),
    path('debts-detail/<int:year>/<int:id>/', login_required(DebtDetailView.as_view()), name="debt_detail"),
    # end debts urls

    # Start over payments
    path('over-payments/<int:year>/', login_required(OverPaymentListView.as_view()), name="over_payments_list"),
    path('over-payment-create/<int:year>/', login_required(OverPaymentCreateView.as_view()),
         name="over_payment_create"),
    path('over-payment-update/<int:year>/<int:id>/', login_required(OverPaymentUpdateView.as_view()),
         name="over_payment_update"),
    path('over-payment-delete/<int:year>/<int:id>/', login_required(over_payment_delete), name="over_payment_delete"),
    path('over-payment-detail/<int:year>/<int:id>/', login_required(OverPaymentDetailView.as_view()),
         name="over_payment_detail"),

    #  end Payments

    # Helpers

    path('inter-org-currency/', login_required(get_currency), name='inter_org_currency')
]

organizations/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .validators import number_validator, phone_nb_validator, currency_validator, file_validator
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.utils.timezone import now

CURRENT_DATE = str(now().strftime('%Y-%m-%d, %H:%M'))


class AuthOrganization(models.Model):

    """
    Vakolatli tashkilot ma'lumotlari
    """

    # Moliyalshtirish manbaasi turlari

    name_uz = models.CharField(max_length=500)
    name_ru = models.CharField(max_length=500)
    name_en = models.CharField(max_length=500)
    address_uz = models.CharField(max_length=255)
    address_ru = models.CharField(max_length=255)
    address_en = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, help_text=_("Email address of authorized organization."))
    phone_number = models.CharField(max_length=13,
                                    validators=[MaxLengthValidator(13), MinLengthValidator(9), phone_nb_validator],
                                    default="+998", help_text=_("Phone number of authorized organization."))
    tax_number = models.CharField(unique=True, max_length=9, null=True, blank=True,
                                  validators=[number_validator])  # Validate!
    inn_code = models.CharField(unique=True, max_length=9, null=True, blank=True,
                                validators=[number_validator])  # Validate!
    deleted = models.BooleanField(default=False)
    deleted_at = models.CharField(default="2021.09.10", blank=True, null=True, max_length=26)

    chief_accountant = models.CharField(max_length=50,
                                        help_text=_("Full name of chief accountant of authorized organization."))
    chief_accountant_phone = models.CharField(max_length=13, validators=[MaxLengthValidator(13), MinLengthValidator(9),
                                                                         phone_nb_validator], default="+998",
                                              help_text=_("Chief accountant phone number."))
    international_department_staff = models.CharField(max_length=50, help_text=_("Staff of international department."))
    inter_dp_phone = models.CharField(max_length=13,
                                      validators=[MaxLengthValidator(13), MinLengthValidator(9), phone_nb_validator],
                                      default="+998", help_text=_("Phone number of international department."))

    def __str__(self):
        return str(self.name_uz)

    class Meta:
        verbose_name = _("Authorized organization")
        verbose_name_plural = _("Authorized organizations")


class Currencies(models.Model):
    """
    Pul birliklari
    """

    name_uz = models.CharField(max_length=25)
    name_ru = models.CharField(max_length=25)
    name_en = models.CharField(max_length=25)
    sign = models.CharField(max_length=1, help_text=_("Currency sign, such as $, €."))
    abbr = models.CharField(max_length=3, validators=[currency_validator],
                            help_text=_("Input the abbreviation for currency."))
    deleted = models.BooleanField(default=False)
    deleted_at = models.CharField(default="2021.09.10", blank=True, null=True, max_length=26)

    def __str__(self):
        return f"{self.name_uz} {self.sign}"

    class Meta:
        verbose_name = "Currency"
        verbose_name_plural = "Currencies"


class InterOrganization(models.Model):
    """
    Xalqaro tashkilot ma'lumotlari
    """

    name_uz = models.CharField(max_length=500)
    name_ru = models.CharField(max_length=500)
    name_en = models.CharField(max_length=500)
    deleted = models.BooleanField(default=False)
    deleted_at = models.CharField(default="2021.09.10", blank=True, null=True, max_length=26)

    # Benefitsiar bank ma'lumotlari

    beneficiary_bank_name = models.CharField(max_length=50, help_text=_("Beneficiary bank's name."))
    bbank_address_uz = models.CharField(max_length=255, help_text=_("Beneficiary bank's address."))
    # bbank_address_ru = models.CharField(max_length=255, help_text=_("Beneficiary bank's address."))
    # bbank_address_en = models.CharField(max_length=255, help_text=_("Beneficiary bank's address."))
    bbank_account_name = models.CharField(max_length=50, help_text=_("Beneficiary bank's account name."))
    bbank_account_number = models.CharField(max_length=50, help_text=_("Beneficiary bank's account number."))
    currency = models.ForeignKey(Currencies, on_delete=models.CASCADE,
                                 help_text=_("The currency unit in which the payment is made"))
    FUNDING_SOURCE_CHOICES = (
        ("in_budget", "Byudjet"),
        ("out_budget", "Byudjetdan tashqari")
    )

    funding_source = models.CharField(max_length=20, choices=FUNDING_SOURCE_CHOICES,
                                      help_text=_("Type of financing resource."))

    # email = models.EmailField(max_length=255)
    # website_url = models.URLField(max_length=255)
    # phone_number = models.CharField(max_length=20)

    def __str__(self):
        return str(self.name_uz)

    class Meta:
        verbose_name = _("International organization")
        verbose_name_plural = _("International organizations")


class LinkedAuthInterOrgs(models.Model):
    """
    O'zbekiston Respublikasining xalqaro shartnomalar
    va xalqaro tashkilotlarga a'zolik bo'yicha
    majburiyatlarni bajarishga mas'ul davlat organlari
    va boshqa tashkilotlar
    """

    auth_organization = models.ForeignKey(AuthOrganization, on_delete=models.CASCADE,
                                          help_text=_("Authorized local organization."))
    inter_organization = models.ForeignKey(InterOrganization, on_delete=models.CASCADE,
                                           help_text=_("International organization."), blank=True, null=True)
    deleted = models.BooleanField(default=False)
    deleted_at = models.CharField(default="2021.09.10", blank=True, null=True, max_length=26)

    def __str__(self):
        return str(self.inter_organization)

    class Meta:
        verbose_name = _("Local and its belonging organization")
        verbose_name_plural = _("Local and its belonging organizations")


class MembershipFeesCondition(models.Model):
    """
    O'zbekiston Respublikasining xalqaro shartnomalar
    va xalqaro tashkilotlarga a'zolik bo'yicha
    mas'ul davlat organlari va boshqa tashkilotlarning
     a'zolik badallarining to'lovi ma'lumotlari
    """
    YEAR_CHOICES = [(f'{y}', f'{y}') for y in range(1991, timezone.now().year + 10)]

    # organizations = models.ForeignKey(LinkedAuthInterOrgs, on_delete=models.CASCADE, default=0)
    auth_organizations = models.ForeignKey(AuthOrganization, on_delete=models.CASCADE, default=1)
    inter_organization = models.ForeignKey(InterOrganization, on_delete=models.CASCADE, default=1)
    fiscal_year = models.CharField(choices=YEAR_CHOICES, help_text=_("Fiscal year"), max_length=4)

    forecast_fee = models.DecimalField(help_text=_("The forecast amount of the membership fee payment"),
                                       decimal_places=2, max_digits=15)
    sent_invoice_sum = models.DecimalField(help_text=_("The amount of invoice sent for the current year"),
                                           decimal_places=2, blank=True, null=True, max_digits=15)
    invoice_confirmation = models.FileField(help_text=_(
        "File on confirmation of  sent invoice  from international organization."), blank=True, null=True,
                                            upload_to='confirmations_invoices/', validators=[file_validator])
    paid_fee = models.DecimalField(help_text=_("The amount of membership fee paid in the current year"),
                                   decimal_places=2, max_digits=15, null=True, blank=True)
    paid_fee_confirmation = models.FileField(help_text=_("File on confirmation of paid fee from local organization."),
                                             upload_to='confirmation_payments/', blank=True, null=True, validators=[file_validator])
    bank_service = models.DecimalField(help_text=_("Bank service fee"), default=0.00, blank=True, null=True, decimal_places=2, max_digits=15)
    payment_confirmed = models.BooleanField(default=False, blank=True, null=True,)
    confirmation_data = models.FileField(upload_to='confirmation_emails/', blank=True, null=True, help_text=_(
        "Information on confirmation of receipt of the amount of membership fee to the international organization"),
                                         validators=[file_validator])  # validate!

    deleted = models.BooleanField(default=False)
    deleted_at = models.CharField(default="2021.09.10", blank=True, null=True, max_length=26)
    create_at = models.DateTimeField(null=True, auto_now_add=True)
    created_by = models.CharField(blank=True, null=True, default='NOT CREATED BY USER', max_length=25)
    payment_date = models.DateField(default=CURRENT_DATE.split(' ')[0].strip(','), blank=True, null=True)

    def __str__(self):
        return f"{self.auth_organizations} - {self.paid_fee}"

    class Meta:
        verbose_name = _("Membership fee condition")
        verbose_name_plural = _("Membership fees condition")


class DebtModel(models.Model):
    """
    Qarzdorlik bo'yicha ma'lumot
    """
    auth_organizations = models.ForeignKey(AuthOrganization, on_delete=models.CASCADE, default=1)
    inter_organization = models.ForeignKey(InterOrganization, on_delete=models.CASCADE, default=1)
    initial_debt = models.DecimalField(decimal_places=2, max_digits=12, blank=True)
    final_debt = models.DecimalField(decimal_places=2, max_digits=15, blank=True)
    fiscal_year = models.CharField(default=str(now().year), help_text=_("Fiscal year"), max_length=4)
    created_at = models.DateTimeField(auto_created=True, blank=True, null=True)

templates/over_paid/over_paid_create.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>Create organizations</title>{% endblock %}

{% block links %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
{% endblock %}





{% block page_title %}
{% trans 'Haqdorlik'%}
{% endblock %}

{% block breadcrumb %}
<div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{% url 'main:home' %}">{% trans 'Bosh sahifa'%}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizations:over_payments_list' year %}">{% trans 'Haqdorlik'%}-{{ year }}</a></li>
      <li class="breadcrumb-item active">{% trans "Qo'shish"%}</li>
    </ol>
</div>
{% endblock %}


    <!-- Main content -->
    {% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-12 mx-auto" style="max-width: 96%">
            <!-- Input addon -->
            <div class="card mt-2">
              <div class="card-header" style="background-color: #0d8ccb">
                <h3 class="card-title">{% trans "Haqdorlik qo'shish"%}</h3>
              </div>
              <div class="card-body">

                <form action="{% url 'organizations:over_payment_create' year %}" method="post">
                    {% csrf_token %}
                    <div class="row mb-2">
                        <div class="col-3">
                            {% if request.user.role == 'Admin' %}
                            {{ form.auth_organizations | as_crispy_field }}
                            {% else %}
                            <label for="user_org">{% trans "Vakolatli tashkilot" %}</label>
                            <input id="user_org" style="font-size: 1.2rem; height: 47.8px" class="form-control d-block" type="text" value="{{ request.user.auth_organization }}" disabled>
                            {% endif %}
                        </div>
                        <div class="col-3">
                            {{ form.inter_organization | as_crispy_field }}
                        </div>
                        <div class="col-3">
                            {{ form.fiscal_year | as_crispy_field }}
                        </div>
                        <div class="col-3">
                            <label for="currency_type_id">{% trans "Pul birligi" %}</label>
                            <input id="currency_type_id" style="font-size: 1.2rem; height: 47.8px" class="form-control d-block" type="text" value="" disabled>
                        </div>
                    </div>
                    <div class="row mt-3 mb-2">
                        <div class="col">
                            <h5 class="font-italic text-secondary">{% trans 'Yil boshidagi haqdorlik'%}. {% trans 'Shundan yillar kesimida'%}:</h5>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col">
                            {{ form.current_1 | as_crispy_field }}
                        </div>
                        <div class="mt-3" style="font-size: 2.3rem">+</div>
                        <div class="col">
                            {{ form.current_2 | as_crispy_field }}
                        </div>
                        <div class="mt-3" style="font-size: 2.3rem">+</div>
                        <div class="col">
                            {{ form.current_3 | as_crispy_field }}
                        </div>
                        <div class="mt-3" style="font-size: 2.3rem">+</div>
                        <div class="col">
                            {{ form.current_4 | as_crispy_field }}
                        </div>
                        <div class="mt-3" style="font-size: 2.3rem">+</div>
                        <div class="col">
                            {{ form.previous_years | as_crispy_field }}
                        </div>
                        <div class="mt-3" style="font-size: 2.3rem">=</div>
                        <div class="col-3">
                            {{ form.initial_amount | as_crispy_field }}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col">
                            {{ form.taken_account | as_crispy_field }}
                        </div>
                        <div class="col">
                            {{ form.final_amount | as_crispy_field }}
                        </div>
                    </div>
                    <div class="row justify-content-end mt-3">
                        <button id="submit_btn" type="submit" class="btn-lg btn-info mr-2">{% trans 'Saqlash'%}</button>
                    </div>
                </form>


              </div>
              <!-- /.card-body -->
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}


{% block script %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Page specific script -->
<script>
$(function () {
  bsCustomFileInput.init();
});
</script>
<script>
$(document).ready(function (){
    $("#currency_type_id").val('USD');
    let url = "{% url 'organizations:inter_org_currency' %}"
    $("#id_inter_organization").on('change', function (){
        let org = $("#id_inter_organization option:selected").val();
        $.ajax({
            url: url,
            data: {
                'org_id': org,
            },
            dataType: 'json',
            success: function (data){
                $("#currency_type_id").val(data['currency_name']);
            },
            fail: function (data){
                $("#currency_type_id").val("------");
                console.log(data);
                console.log('failed');
            }
        })
    });


    $("#id_fiscal_year").val({{ year }});
    $("#id_initial_amount").val(0);
    let current_1 = parseInt($("#id_current_1").val());
    let current_2 = parseInt($("#id_current_2").val());
    let current_3 = parseInt($("#id_current_3").val());
    let current_4 = parseInt($("#id_current_4").val());
    let current_5 = parseInt($("#id_previous_years").val());


    $("#id_current_1").on("change", function(){
        if (parseInt($(this).val()) != current_1){
            $("#id_initial_amount").val(parseInt($("#id_initial_amount").val()) + parseInt($(this).val()) - current_1)
        };
        current_1 = parseInt($("#id_current_1").val());
        {#let initial_value = parseInt($("#id_initial_value").val());#}

    });
    $("#id_current_2").on("change", function(){
        if (parseInt($(this).val()) != current_2){
            $("#id_initial_amount").val(parseInt($("#id_initial_amount").val()) + parseInt($(this).val()) - current_2)
        };
        current_2 = parseInt($("#id_current_2").val());
        {#let initial_value = parseInt($("#id_initial_value").val());#}
    })
    $("#id_current_3").on("change", function(){

        if (parseInt($(this).val()) != current_3){
            $("#id_initial_amount").val(parseInt($("#id_initial_amount").val()) + parseInt($(this).val()) - current_3)
        };
        current_3 = parseInt($("#id_current_3").val());
        {#let initial_value = parseInt($("#id_initial_value").val());#}
    });
    $("#id_current_4").on("change", function(){
        if (parseInt($(this).val()) != current_4){
            $("#id_initial_amount").val(parseInt($("#id_initial_amount").val()) + parseInt($(this).val()) - current_4)
        };
        current_4= parseInt($("#id_current_4").val());
        {#let initial_value = parseInt($("#id_initial_value").val());#}
    });
    $("#id_previous_years").on("change", function(){
        if (parseInt($(this).val()) != current_5){
            $("#id_initial_amount").val(parseInt($("#id_initial_amount").val()) + parseInt($(this).val()) - current_5)
        };
        current_5 = parseInt($("#id_previous_years").val());
        {#let initial_value = parseInt($("#id_initial_value").val());#}
    });

    let taken_account = parseInt($("#id_taken_account").val());

    $("#id_taken_account").on("change", function (){
        if (parseInt($(this).val()) != taken_account){
            $("#id_final_amount").val(parseInt($("#id_initial_amount").val()) - parseInt($(this).val()) + taken_account)
        };
        taken_account = parseInt($("#id_final_amount").val());
    });

    $("#submit_btn").on('click', function(){
        $("#id_fiscal_year").value = {{ year }};

        $("#id_initial_amount").value = parseInt($("#id_current_1").val())+parseInt($("#id_current_2").val())+parseInt($("#id_current_3").val())+parseInt($("#id_current_4").val())+parseInt($("#previous_years").val());
        $("#id_final_amount").value = parseInt($("#id_initial_debt").val())-parseInt($("#id_taken_account").val());
        return true;
    })
})
</script>


{% endblock %}

templates/over_paid/over_paid_delete.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>Delete organizations</title>{% endblock %}

{% block links %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
{% endblock %}





{% block page_title %}
{% trans 'Haqdorlik'%}
{% endblock %}

{% block breadcrumb %}
<div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{% url 'main:home' %}">{% trans 'Bosh sahifa'%}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'organizations:over_payments_list' year %}">{% trans 'Haqdorlik'%}-{{ year }}</a></li>
      <li class="breadcrumb-item active">{% trans "O'chirish"%}</li>
    </ol>
</div>
{% endblock %}


    <!-- Main content -->
    {% block content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-12 mx-auto" style="width: 96%">
            <!-- Input addon -->
            <div class="card mt-2">
              <div class="card-header" style="background-color: #0d8ccb">
                <h3 class="card-title">{% trans "Haqdorlikni o'chirish"%}</h3>
              </div>
              <div class="card-body">

                <form action="{% url 'organizations:over_payment_delete' year object.id %}" method="post">
                    {% csrf_token %}
                    <table id="example1" class="table table-bordered table-hover text-center">
                      <thead class="bg-gray-light">
                      <tr>
                        <th>T/r</th>
                        <th>{% trans 'Vakolatli tashkilot'%}</th>
                        <th>{% trans 'Xalqaro tashkilot'%}</th>
                        <th>{% trans 'Yil boshidagi haqdorlik'%}</th>
                        <th>{% trans 'Yil oxiridagi haqdorlik'%}</th>
                      </tr>
                      </thead>
                      <tbody>
                      <tr>
                        <td>{{ object.id }}</td>
                        <td>{{ object.auth_organizations }}</td>
                        <td>{{ object.inter_organization }}</td>
                        <td>{{ object.initial_amount }}</td>
                        <td>{{ object.final_amount }}</td>
                      </tr>
                      </tbody>
                    </table>
                    <div class="row ml-2 mt-3">
                        <button id="delete_btn" type="submit" class="btn-lg  btn-danger" onclick="return confirm('Buyruqni tasdiqlaysizmi?')"><i class="fas fa-trash"></i></button>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}
{% block script %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Page specific script -->
{% endblock %}